# Generated by Django 5.2.4 on 2025-07-23 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CementFactoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('paid_up', models.IntegerField(help_text='Paid-up capital in rupees')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSectionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_date', models.DateTimeField()),
                ('news_image', models.ImageField(upload_to='news_images/')),
                ('news_body', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_factory.cementfactoryinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='app_factory.cementfactoryinfo')),
            ],
        ),
    ]
